name: Deploy to GitHub pages

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run the build
        run: |
          npm install
          npm run build